


version: '3.9'

services:

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: event-sourcing
    volumes:
      - ./.mongo-data:/data/db



  integration-test-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: test-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test-integration-db
      MYSQL_PASSWORD: password
    ports:
      - "33010:3306"
    volumes:
      - ./.test-mysql-data:/var/lib/mysql

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: nodejs-rabbitmq-rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  # app:
  #     build: .
  #     ports:
  #       - "3000:3000"
  #     volumes:
  #       - .:/app
  #       - /app/node_modules
  #     stdin_open: true
  #     tty: true


